version: '3.8'

services:
  backend:
    build: ./backend
    container_name: transfer-backend
    ports:
      - "5500:5500"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/transferdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    networks:
      - transfer-network

  db:
    image: postgres:13
    container_name: transfer-db
    environment:
      - POSTGRES_DB=transferdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transfer-network

networks:
  transfer-network:
    driver: bridge

volumes:
  postgres_data: